### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by mcgr0217** [mcgr0217/portfolio#12]
Hey Thomas,

Not sure why but when I look at my site on (http://127.0.0.1:4000/) Everything works and seems to be fine but when I look at my actual URL that I submitted to you my image links are broken and the video doesnt play. The video I placed isnt the actual video I will use but it's just a placeholder for now to see if it works.

When I inspect the element it says that the page cannot be found and it says it's in the jekyll folder but its in my portfolio folder so i'm not too sure with how to fix this...

<img width="332" alt="screen shot 2015-10-21 at 12 41 30 pm" src="https://cloud.githubusercontent.com/assets/6340278/10643574/97db8548-77f1-11e5-8e07-016ddfa00919.png">
<img width="673" alt="screen shot 2015-10-21 at 12 41 51 pm" src="https://cloud.githubusercontent.com/assets/6340278/10643575/97db82c8-77f1-11e5-80c0-bff64190e12e.png">
<img width="744" alt="screen shot 2015-10-21 at 12 42 06 pm" src="https://cloud.githubusercontent.com/assets/6340278/10643576/97db8f8e-77f1-11e5-82ed-4ddcfa45e1aa.png">
<img width="640" alt="screen shot 2015-10-21 at 12 42 16 pm" src="https://cloud.githubusercontent.com/assets/6340278/10643573/97db2102-77f1-11e5-9df2-5109f2910f04.png">
<img width="777" alt="screen shot 2015-10-21 at 12 42 22 pm" src="https://cloud.githubusercontent.com/assets/6340278/10643577/97dbea42-77f1-11e5-9285-8b85135f20b7.png">

@thomasjbradley

**Comment by mcgr0217** [comment]
<img width="692" alt="screen shot 2015-10-21 at 12 47 48 pm" src="https://cloud.githubusercontent.com/assets/6340278/10643684/223f5390-77f2-11e5-99ce-69014f9a3240.png">

**Comment by thomasjbradley** [comment]
I looks like the `{{site.baseurl}}` is just in the wrong place. Looking at this code here:
https://github.com/mcgr0217/portfolio/blob/gh-pages/index.html#L53

The `site.baseurl` is inside of `class` instead of `src`.
Probably a similar thing for the video.

**Comment by mcgr0217** [comment]
Thanks Thomas I fixed the problem!
