### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by mcgr0217** [mcgr0217/portfolio#14]
Hey Thomas, I just noticed when I view my website on the preview browser it shows my images behind the text but when I view it on the actual site it doesn't show up and I inspected the element and it said that it was trying to take the images from the jekyll folder and not the portfolio folder and i'm unsure on how to make it search the portfolio folder instead.
@thomasjbradley 

<img width="839" alt="screen shot 2015-11-15 at 12 56 34 pm" src="https://cloud.githubusercontent.com/assets/6340278/11170101/cbccd310-8b98-11e5-974c-3fb3d78ebcbf.png">
<img width="877" alt="screen shot 2015-11-15 at 12 56 07 pm" src="https://cloud.githubusercontent.com/assets/6340278/11170102/cfc64bea-8b98-11e5-9d21-88c506f3b699.png">

**Comment by thomasjbradley** [comment]
The `baseurl` property inside of `_config.yml` is pointing to the wrong folder:
https://github.com/mcgr0217/portfolio/blob/gh-pages/_config.yml#L2

It should probably be:

``` yml
baseurl: /portfolio
```

**Comment by mcgr0217** [comment]
Thanks!
