### ISSUE TITLE
Safari 9 and iOS 9 testing 

### ISSUE THREAD

**Issue by shaayaanjameel** [mcgr0217/portfolio#2]
Safari 9 & iOS 9 - Your navigation links and photography link are not working. 

When the browser size changes the navigation moves to the left side (which is fine), but it is cutting thru the other stuff on your page so it overlaps at times. 

Your email and phone number are too close to each other, when I clicked on your e-mail it redirected me as if I clicked on your phone number. 

iOS 9 - Your images are no longer centered

**Comment by marissagodwin** [comment]
Same for Opera on iOS
